# Server
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mechinow_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
spring.application.name=mechinow-backend